import Head from "next/head";
import Promo from "../components/Promo";
import About from "../components/About";

export default function Home() {
  return (
    <>
      <Head>
        <title>homie43 portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <Promo />
        <About />
      </main>
    </>
  );
}
